### ISSUE TITLE
Use Terraform for creating infrastructure

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1000]
See https://www.terraform.io

Additional resources:
- https://www.terraform.io/docs/providers/do/index.html
- https://www.digitalocean.com/docs/api/create-personal-access-token/
- https://www.terraform.io/docs/providers/mailgun/index.html
- https://github.com/louy/terraform-provider-uptimerobot

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1212](https://github.com/php-coder/mystamps/issues/1212) is still not solved.
