### ISSUE TITLE
Remove support for sending e-mails via SMTP

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1022]
Extracted from https://github.com/php-coder/mystamps/issues/935#issuecomment-490219619:

- `application*.properties`: remove `spring.mail.*` properties
- `application*.properties`: exclude `MailSenderAutoConfiguration`
- ansible: remove `user_mail_password` variable
- `pom.xml`: consider removing dependency on `spring-boot-starter-mail`

Tech debt for: #935

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1092](https://github.com/php-coder/mystamps/issues/1092) is still not solved.
