### ISSUE TITLE
/series/sales/import: validate that we have a parser for this url

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1027]
The puzzle `995-f9b468d5` from #995 has to be resolved: 

https://github.com/php-coder/mystamps/blob/bc3fe55ea8748c0231f45e6f403419e6b0a02df8/src/main/java/ru/mystamps/web/feature/series/importing/RequestImportForm.java#L42-L42

The puzzle was created by Slava Semushin on 03-Jun-19.

**Comment by php-coder** [comment]
Possible error message: "Import from the provided site isn't supported".

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1079](https://github.com/php-coder/mystamps/issues/1079) is still not solved.
