### ISSUE TITLE
SeriesSalesImportServiceImpl.downloadAndParse(): add unit tests

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1028]
The puzzle `995-950efed9` from #995 has to be resolved: 

https://github.com/php-coder/mystamps/blob/bc3fe55ea8748c0231f45e6f403419e6b0a02df8/src/main/java/ru/mystamps/web/feature/series/importing/sale/SeriesSalesImportServiceImpl.java#L42-L42

The puzzle was created by Slava Semushin on 03-Jun-19.

**Comment by php-coder** [comment]
Closed by 68030d236983ade8c7e4e7a3fee61bcdc2a555fd commit.
