### ISSUE TITLE
Import series sale form: port to React

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1057]

**Comment by 0pdd** [comment]
@php-coder 5 puzzles [#1072](https://github.com/php-coder/mystamps/issues/1072), [#1073](https://github.com/php-coder/mystamps/issues/1073), [#1074](https://github.com/php-coder/mystamps/issues/1074), [#1075](https://github.com/php-coder/mystamps/issues/1075), [#1076](https://github.com/php-coder/mystamps/issues/1076) are still not solved.
