### ISSUE TITLE
Provide an endpoint for logging CSP violations

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1058]
In order to be notified about Content Security Policy violations, we need to have an endpoint which just prints the report to the log.

Here is an example of such a report (but it's just for information): https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#Sample_violation_report

Requirements:
- add new controller (`CspController`) in `ru.mystamps.web.feature.site` package
- add the endpoint that accepts POST requests on `/site/csp/reports` and outputs the request body to log

Part of #226

**Comment by php-coder** [comment]
@MainStar Hi, let me know if you need a help.

**Comment by MainStar** [comment]
Hi, yes sure, I just need some time, cuz now I am in vacation, and then I will relocate to another city, and I will need to organize it.12.07.2019, 00:55, "Slava Semushin" <notifications@github.com>:@MainStar Hi, let me know if you need a help.

**Comment by php-coder** [comment]
@MainStar Ok, thanks for the information! Ping me when the dust will settle down :)

**Comment by MainStar** [comment]
Yes, sure :)12.07.2019, 12:24, "Slava Semushin" <notifications@github.com>:@MainStar Ok, thanks for the information! Ping me when the dust will settle down :)

**Comment by php-coder** [comment]
@MainStar I'm sorry but as I want to push this task forward, I had to re-assign it from you.

**Comment by MainStar** [comment]
Hi, Ok, no problem.16.07.2019, 00:41, "Slava Semushin" <notifications@github.com>:@MainStar I'm sorry but as I want to push this task forward, I had to re-assign it from you.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1094](https://github.com/php-coder/mystamps/issues/1094) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the only puzzle [#1094](https://github.com/php-coder/mystamps/issues/1094) is solved here.
