### ISSUE TITLE
Configure infrastructure to be able to use ES6 and React

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1060]
Prerequisite for: #1056 and #1057

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#1070](https://github.com/php-coder/mystamps/issues/1070), [#1071](https://github.com/php-coder/mystamps/issues/1071) are still not solved.

**Comment by php-coder** [comment]
I've added everything that I planned. Done.
