### ISSUE TITLE
Search by catalog number: add integration test to check that catalogNumber is specified

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1065]
Create the following test:
- open a main page
- click on the `Search` button
- test that "Number" field has an error `Value must not be empty`

Requirements:
- the test should be located in the `src/test/robotframework/series/search/validation.robot` file

Hint:
- we can use `src/test/robotframework/category/creation/validation.robot` file as an example

Extracted from #340 to reduce the scope.

**Comment by mukeshk** [comment]
Do we need to add an id attribute to the search form "Search by catalog" on the html?
For the test case step :  
>> Submit Form             id=

**Comment by php-coder** [comment]
Thank you for the question!

> Do we need to add an id attribute to the search form "Search by catalog" on the html?

Yes, sure. You can find the form in the `src/main/webapp/WEB-INF/views/site/index.html` file. Let's use `search-series-form` as id.

By the way, in order to locate the error message, we also will need id. I suggest to name it `catalogNumber.errors`

**Comment by php-coder** [comment]
@mukeshk If you work on this issue, please, assign it to yourself (and, optionally, add "in progress" label).
