### ISSUE TITLE
Search by catalog number: add integration test for an empty result

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1066]
Create the following test:

- open a main page
- fill `Search by catalog` form:
  - provide non-existent catalog number (let's say 888)
  - chose a catalog (let's pick a random one from Michel/Scott/Yvert/Gibbons) 
  - click on the `Search` button
- ensure that the resulted page contains the message `No series found`

Requirements:
- the test should be located in the `src/test/robotframework/series/search/logic.robot` file

Hint:
- Could be useful: https://stackoverflow.com/questions/28039417/any-builtin-in-robot-framework-for-selecting-a-random-value-from-the-dropdown-li

Extracted from #340 to reduce the scope.

**Comment by mukeshk** [comment]
https://stackoverflow.com/questions/55791753/robot-framework-random-selection-of-drop-downs.

Can we use this solution?

**Comment by mukeshk** [comment]
<p class="text-center">No series found</p> - should we add an id to this element for checking the text value ?

**Comment by php-coder** [comment]
> https://stackoverflow.com/questions/55791753/robot-framework-random-selection-of-drop-downs.
> Can we use this solution?

Unfortunatelly, no, we can't use it because it requires a library on Python while we use Robot Framework that is running under JVM. Anyway, it makes a little sense to add a dependency on a library for just a few lines.

> should we add an id to this element for checking the text value ? 

Definitely, we should. In most of the cases, when there is no id, we should add it.

**Comment by mukeshk** [comment]
Ok. No problem. I was not aware of the dependency. Agree no need to add for
this requirement.
 Will check.

Thanks

**Comment by mukeshk** [comment]
![image](https://user-images.githubusercontent.com/1241720/60878293-146f2f80-a25d-11e9-8ba6-859c3bba05e7.png)

**Comment by mukeshk** [comment]
I am able to access the list. I get the length of items. Is there any way I can get a random number between 0 and ListLength-1. which I can pass use for setting the selected index.

**Comment by php-coder** [comment]
> Is there any way I can get a random number between 0 and ListLength-1. which I can pass use for setting the selected index.

Hey, good question! Thank you!

It seems that we can use `Evaluate` keyword and  execute `random.randint()` function from Python:
- http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluate
- http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluating%20expressions
- https://docs.python.org/2/library/random.html#random.randint

**Comment by php-coder** [comment]
P.S. Could you, please, create a separate keyword `Select Random Option From List` for that and put it to `src/test/robotframework/selenium.utils.robot` so we can re-use it across the tests? This keyword from get a locator of the `<select>` element and choose a random option from this element.

**Comment by mukeshk** [comment]
Yes.

Search non existent catalog number results in no series found
	Input Text              id=catalogNumber  888
	${catalogItems} =   Get List Items    catalogName
    ${catalogListLength}=    Get Length    ${catalogItems}
    ${randomCatalogIndex}=  Evaluate  random.randint(0,${catalogListLength})    random
    log to console  \nvalue: ${randomCatalogIndex}
	Select from list by index   catalogName    ${randomCatalogIndex}
	Submit Form             id=search-series-form
	Element Text Should Be  id=no-series-found  No series found

**Comment by mukeshk** [comment]
I will try to move a few steps to reusable keyword

**Comment by php-coder** [comment]
If you have some code, why not submit it as a pull request? Just prepend PR's title with `[WIP]` to show that you still work on it. In this case, it will be easier to me to help you and I'll be able to put a commit on a particular line, for example.
