### ISSUE TITLE
Find a way to make ErrorProne work in IntelliJ IDEA

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1069]
Compilation fails with the following error when it's being run in IDEA:

> Error:java: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V

It's a known issue (https://github.com/google/error-prone/issues/535) and it seems like installing ErrorProne plugin (https://errorprone.info/docs/installation) should solve it. Need to test it and update documentation.

If it doesn't work, we should mention it in the documentation (for instance, in `README.md`) anyway.

Reported by @mukeshk

**Comment by php-coder** [comment]
A way to activate a certain Maven profile only within IDEA: https://stackoverflow.com/questions/24760387/activate-certain-maven-profile-in-intellij-idea-only

**Comment by peterdemaeyer** [comment]
I just ran into this when cloning a fresh santuario-java from Bitbucket.
"mvn clean install" works, but IntelliJ refuses to build it, even after I install the Error Prone Compiler plugin.
I haven't found a solution yet.

```
Information:javac 1.8.0_232 was used to compile java sources
Information:27/01/20 23:19 - Build completed with 4 errors and 0 warnings in 1 s 867 ms
Error:java: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: 	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:202)
Error:java: 	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:40)
```

**Comment by php-coder** [comment]
@peterdemaeyer Hey Peter and thanks for letting me know! Now I know that I'm not alone who has faced this :) It would be great to file an issue in IDEA issue tracker. If you would do this, please, let me know as well.

**Comment by jmayday** [comment]
> I just ran into this when cloning a fresh santuario-java from Bitbucket.
> "mvn clean install" works, but IntelliJ refuses to build it, even after I install the Error Prone Compiler plugin.
> I haven't found a solution yet.

But did you amend settings accordingly? 
![image](https://user-images.githubusercontent.com/10167533/74595484-0890ea80-5042-11ea-8385-d73cddc656da.png)

**Comment by peterdemaeyer** [comment]
Ah, indeed, that was it, thanks!

**Comment by asm0dey** [comment]
Do you know guys that you can share IDEA settings in git and everybody will
have the same setup?
Also did you try to delegate build to maven from IDEA?

вс, 16 февр. 2020 г. в 12:01, Peter De Maeyer <notifications@github.com>:
