### ISSUE TITLE
Danger: handle Babel errors from frontend-maven-plugin

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1071]
The puzzle `1060-a747d278` from #1060 has to be resolved: 

https://github.com/php-coder/mystamps/blob/1dc70fd43f6c68ba6890343d7aaf1097172c5f01/Dangerfile#L408-L408

The puzzle was created by @php-coder on 10-Jul-19.

**Comment by php-coder** [comment]
I have decided discontinue usage of Danger (see #1600).
