### ISSUE TITLE
Make React related integration tests work

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1072]
The puzzle `1057-d01039f1` from #1057 has to be resolved: 

https://github.com/php-coder/mystamps/blob/6b40dca8499988b21a1c8cdda049588f3687a4b1/pom.xml#L1061-L1061

The puzzle was created by @php-coder on 23-Jun-19.

**Comment by php-coder** [comment]
At this moment, they fail with:
```
Import a series sale with invalid url                                 | FAIL |
ReferenceError: "Headers" is not defined. (http://127.0.0.1:8080/public/react-dom/16.8.6/umd/react-dom.production.min.js#17)
```
Most likely, this will be fixed with a new version of Selenium and htmlunit (see #1001)

**Comment by php-coder** [comment]
We can try to use axios instead or wait until #966 will be solved.

**Comment by php-coder** [comment]
With axious everything works except `sendKeys()` that might fail: https://github.com/HtmlUnit/htmlunit/issues/142

**Comment by php-coder** [comment]
Done.
