### ISSUE TITLE
Series sale import: add integration test to check that URL can be parsed

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1079]
The puzzle `1027-ca188b93` from #1027 has to be resolved: 

https://github.com/php-coder/mystamps/blob/16c3c75e749f36ea21beb62aee95e458190ed788/src/main/java/ru/mystamps/web/feature/series/importing/HasSiteParser.java#L32-L32

The puzzle was created by Slava Semushin on 14-Jul-19.

**Comment by php-coder** [comment]
This issue is similar to #1080 but on another page.
