### ISSUE TITLE
Series import: add integration test to check that URL can be parsed

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1080]
The puzzle `690-f7dcd2e7` from #690 has to be resolved: 

https://github.com/php-coder/mystamps/blob/16c3c75e749f36ea21beb62aee95e458190ed788/src/main/java/ru/mystamps/web/feature/series/importing/HasSiteParser.java#L31-L31

The puzzle was created by Slava Semushin on 14-Jul-19.

**Comment by php-coder** [comment]
This issue is similar to #1079  but on another page.
