### ISSUE TITLE
Search by catalog number in user's collection: add a prototype

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1087]
This is part of #673

**Acceptance criteria**:
- add a checkbox to Search series form on the main page
- checkbox should have a title `In my  collection` (or `В моей коллекции` in Russian)
- checkbox shouldn't be selected by default
- add feature toggle `SEARCH_IN_COLLECTION` to the [`Features`](https://github.com/php-coder/mystamps/blob/25c9b54dcd5d66e0148f3fc7f78df6d7e7f04ace/src/main/java/ru/mystamps/web/support/togglz/Features.java) file
- new feature should be disabled by default
- checkbox should be visible only when new feature is active AND user is authenticated (use Spring Security attributes for Thymeleaf)

**Comment by mukeshk** [comment]
Is the server-side API ready to handle this request param?
Or it's just UI story at the moment

**Comment by mukeshk** [comment]
![image](https://user-images.githubusercontent.com/1241720/61622126-d11bb480-ac91-11e9-80c0-8137600d04e8.png)

**Comment by php-coder** [comment]
Yeah, something like this. Let's put checkbox first, before title and remove a colon also.
