### ISSUE TITLE
/site/csp/reports: add integration tests

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1094]
The puzzle `1058-2b82d429` from #1058 has to be resolved: 

https://github.com/php-coder/mystamps/blob/891667cb52ed9a025bf3eec018586046d3f4e3ae/src/main/java/ru/mystamps/web/feature/site/CspController.java#L31-L31

The puzzle was created by Slava Semushin on 21-Jul-19.

---

Add a test that submit a request to `/site/csp/reports` and ensures that it returns 204 status code.

Requirements:
* the test should be located in the `src/test/robotframework/site/csp/report-logic.robot` file

Hint:
* use `src/test/robotframework/account/registration/logic.robot` as example
* keywords: http://central.maven.org/maven2/com/github/hi-fi/robotframework-httprequestlibrary/0.0.15/robotframework-httprequestlibrary-0.0.15.html

**Comment by php-coder** [comment]
@annazarubina This is a new task. See also https://github.com/php-coder/mystamps/blob/master/docs/robotframework.md

**Comment by php-coder** [comment]
@annazarubina Let me know if you still interested in working on this.
