### ISSUE TITLE
Search by catalog number in user's collection: add the simplest implementation

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1098]
Here is the simplest implementation that even doesn't introduce new methods:

- modify `SeriesController.searchSeriesByCatalog()` method to do the following:
  - after search for series in database (see `switch`) but right before passing the results to a view (`model.addAttribute()`)
     - if feature is enabled
     - and if checkbox is selected
     - and if a user isn't anonymous
     - iterate over results and filter out the series that a user doesn't have in its collection (use `CollectionService.isSeriesInCollection()`)

Yeah, this is kind of ugly, use extra memory, leads to N+1 query to database but it's fastest approach to implement without adding a lot of code.

This is part of #673

**Comment by mukeshk** [comment]
I looked at the model SeriesInfoDto which is returned by the repository.  We have an Id attribute in there.
This Id attribute needs to be checked against the User  Series.
1. How do we know about the Series in a User collection?
2. Did not find CollectionSeries.isSeriesInCollection() method ?

**Comment by php-coder** [comment]
> Did not find CollectionSeries.isSeriesInCollection() method ?

Whoops, I mean `CollectionService`: https://github.com/php-coder/mystamps/blob/f61614416bf4b6560ac7451deeb0f78e716c9a70/src/main/java/ru/mystamps/web/feature/collection/CollectionService.java#L30

**Comment by php-coder** [comment]
> How do we know about the Series in a User collection?

`CollectionService.isSeriesInCollection()` method should help us -- we provide a user and a series and it gives an answer to the question "whether this series in a collection of this user".

**Comment by mukeshk** [comment]
Ok. This means we need to iterate over records and call the api for each
record.
Collect the matching elements and send in the response.

Do we have a batch API to check the series id?

Thanks

**Comment by php-coder** [comment]
> Ok. This means we need to iterate over records and call the api for each
record. Collect the matching elements and send in the response.

Yes, that's correct.

> Do we have a batch API to check the series id?

Not yet. Could be added in one of the iterations later.

At this point, we'll check one by one.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1101](https://github.com/php-coder/mystamps/issues/1101) is still not solved.
