### ISSUE TITLE
Include userId in log messages by using MDC

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1102]
Acceptance criteria:
- every log message contains userId

How to achieve that:
- add Servlet Filter that puts userId into MDC
- modify log pattern to include a userId from MDC

Hint:
- see #388 for links and materials about MDC
- let's extend [`OncePerRequestFilter`](https://docs.spring.io/spring-framework/docs/4.3.4.RELEASE/javadoc-api/org/springframework/web/filter/OncePerRequestFilter.html) (see also https://stackoverflow.com/questions/13152946/what-is-onceperrequestfilter)

Part of #388

**Comment by mukeshk** [comment]
How about an anonymous user?

**Comment by php-coder** [comment]
In this case, log message will contain an empty userId. The same for Spring Boot logs or repeated tasks that we run for maintenance.

Another option is to use 0 UID as it never exists. Let's use the first approach and will change it if necessary.
