### ISSUE TITLE
Detect trailing spaces in *.robot files

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1104]
A couple of times I've merged PRs and I've noticed trailing spaces in the `*.robot` files too late. We need to detect such violations and fail earlier.

`rflint` should support it, but it doesn't: https://github.com/boakley/robotframework-lint/issues/37

So, here what we can do:
- contribute such a support to rflint
- [write a custom rule](https://github.com/boakley/robotframework-lint/wiki) for rflint
- add a simple check to Danger (it could be just a single `grep` invocation)

**Comment by php-coder** [comment]
> A couple of times I've merged PRs

Here is the commits where I had to fix trailing spaces:
- 3672a31f67adad888e3f20a8c0d42f30f92e19e1
- da0ba7eeedd46db1558b5c0a0ce8325b5aea3c98
- ea7d9c34a8f72e559ad2553d10551eddc351af57

As I see, we need to detect this not only for *.robot files but also for HTML content.

**Comment by php-coder** [comment]
One more: faf54746c092fdeda904bd591f5802389f3b6ad1

**Comment by php-coder** [comment]
Yet another one: 5d78e2b585711008c73c13c88d086c765dc5e8d0

**Comment by mukeshk** [comment]
I will double-check on next commits.

**Comment by php-coder** [comment]
@mukeshk I don't blame you as it should be spotted by our scripts. I also haven't noticed it during review so this is something that just should be automated.

**Comment by php-coder** [comment]
One more: f62ebd22542122177aa463fbc349d700426ba5d7
