### ISSUE TITLE
Togglz: remove items left from >= 0.4.1 milestone

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1121]
The puzzle `605-2e5a00b2` from #605 has to be resolved: 

https://github.com/php-coder/mystamps/blob/41b4250c1cebdd4dcf676378654c7a6345a4827e/src/main/java/ru/mystamps/web/support/togglz/Features.java#L25-L25

The puzzle was created by Slava Semushin on 09-Sep-19.

**Comment by php-coder** [comment]
I looked on prod and I see that Togglz doesn't persist all these old features:
```
mysql> select * from TOGGLZ;
+---------------------------------+-----------------+-------------+-----------------+
| FEATURE_NAME                    | FEATURE_ENABLED | STRATEGY_ID | STRATEGY_PARAMS |
+---------------------------------+-----------------+-------------+-----------------+
| ADD_ADDITIONAL_IMAGES_TO_SERIES |               1 | NULL        | NULL            |
| CSP_REPORT_ONLY                 |               0 | NULL        | NULL            |
+---------------------------------+-----------------+-------------+-----------------+
2 rows in set (0.00 sec)
```
So, only `ADD_ADDITIONAL_IMAGES_TO_SERIES` needs to be cleaned up in this case.
