### ISSUE TITLE
User can add multiple instances of a series into a collection

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1123]
To be done:
- [x] relax constraints on database level (#986)
- [x] make it possible to add more than one instance of a series
- [x] update a view to show a list of series
- [x] make it possible to delete only one instance of a series from a collection
- [x] protect deletion against removing someone's else instance (we've already protected by the SQL query that we use)
- [x] don't show "New" badge multiple times (I'll deal with it in a separate issue)
- [x] customize "Series isn't part of your collection" message => "Add another one instance of this series to collection"
- [x] integration test
  - [x] the form is visible again
  - [x] the message has been changed
  - [x] a number of stamps is displayed

**Comment by php-coder** [comment]
It seems like using `UUID` type isn't good idea:
- it can be slow: http://www.h2database.com/html/functions.html#random_uuid
- it is supported by MySQL only since version 8
- even if we would have the latest version of MySQL, Liquibase seems doesn't know about it: https://github.com/liquibase/liquibase/blob/02ffb85e1028038d8c07821fe89575e70c137526/liquibase-core/src/main/java/liquibase/datatype/core/UUIDType.java#L39

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#1193](https://github.com/php-coder/mystamps/issues/1193), [#1194](https://github.com/php-coder/mystamps/issues/1194) are still not solved.
