### ISSUE TITLE
Unify PostgreSQL version/configuration between Travis and docker-compose

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1141]
The puzzle `1054-10af1a0a` from #1054 has to be resolved: 

https://github.com/php-coder/mystamps/blob/d4b807358d770e34dc7676a04a6967a9c8bad63e/.travis.yml#L18-L18

The puzzle was created by Slava Semushin on 19-Oct-19.

**Comment by php-coder** [comment]
At this moment, on Travis CI we use PostgreSQL 9.6.15
