### ISSUE TITLE
Terraform: add UptimeRobot

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1301]
The puzzle `1000-6a846ef7` from #1000 has to be resolved: 

https://github.com/php-coder/mystamps/blob/8e7e2e57044880001f94af876a3f06706ce31c96/infra/terraform/my-stamps.tf#L2-L2

The puzzle was created by @php-coder on 23-Mar-20.

**Comment by php-coder** [comment]
See https://github.com/louy/terraform-provider-uptimerobot
