### ISSUE TITLE
Hidden images: admin can hide an image

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1383]
The puzzle `1356-1188ca31` from #1356 has to be resolved: 

https://github.com/php-coder/mystamps/blob/01dca27e62e30b93b5c35f0c7d8d1fee0c705658/src/main/webapp/WEB-INF/views/series/info.html#L173-L173

The puzzle was created by Slava Semushin on 04-May-20.

**Comment by php-coder** [comment]
Perhaps, adding a hidden image might be more useful at this point. While we can add an image and hide it later, it has a side-effect where series updated_at time is changing.

**Comment by php-coder** [comment]
We should show a form for hiding images only when a series has more than one image.

Other thoughts: do we need to make an image visible again?

**Comment by php-coder** [comment]
Done.
