### ISSUE TITLE
AddCatalogPriceForm: show a currency

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1388]
The puzzle `1342-ddac07e5` from #1342 has to be resolved: 

https://github.com/php-coder/mystamps/blob/86959e0c97d5fe95753afaed57047bed19279392/src/main/frontend/src/components/AddCatalogPriceForm.js#L5-L5

The puzzle was created by Bakhodyr Kadyrov on 09-May-20.

**Comment by php-coder** [comment]
We should update markup and show a currency like on a series creation page:

https://github.com/php-coder/mystamps/blob/86959e0c97d5fe95753afaed57047bed19279392/src/main/webapp/WEB-INF/views/series/add.html#L378-L514

In other words, when Michel catalog is chosen, currency should be EUR. For Scott it will be USD and so on.
