### ISSUE TITLE
Update series: add validation for a comment

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1411]
The puzzle `785-b7c2e7d1` from #785 has to be resolved: 

https://github.com/php-coder/mystamps/blob/7be4e62acf67e49399209dfe1cb5746759cab445/src/main/java/ru/mystamps/web/feature/series/RestSeriesController.java#L44-L44

The puzzle was created by Slava Semushin on 24-May-20.

**Comment by php-coder** [comment]
Валидация на длину строки:

https://github.com/php-coder/mystamps/blob/71462673783b6048a5faefcecc0302cdd9a07990/src/main/java/ru/mystamps/web/feature/series/AddSeriesForm.java#L145-L146

https://github.com/php-coder/mystamps/blob/71462673783b6048a5faefcecc0302cdd9a07990/src/test/robotframework/series/creation/validation-admin.robot#L56-L62

+ надо реализовать удаление "висячих" пробелов:

https://github.com/php-coder/mystamps/blob/71462673783b6048a5faefcecc0302cdd9a07990/src/test/robotframework/series/creation/misc-admin.robot#L11-L16

**Comment by php-coder** [comment]
> надо реализовать удаление "висячих" пробелов

Оно уже есть. См. `PatchRequest.setValue()`
