### ISSUE TITLE
Reduce a number of collaborators on GitHub

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#1517]
We have 10 collaborators and most of them aren't active. Because collaborator's status grants some privileges for this repository, reducing a number of collaborators potentially could protect the repo against malicious access in case one of the collaborators loose its credentials.

@annazarubina @ArtemFedorchuk @asm0dey @bahoss @demianova @MainStar @milik27 @mscibilia @mukeshk @splin-shady Guys and gals, if you plan to continue to contribute to this repository, please, leave a comment. Otherwise, in a 1 month, I'll revoke the collaborator access from your accounts.

If you don't reply, it means that you don't mind to loose the collaborator's access. You can get it back anytime later, when you contribute again.

Thank you for all your help anyway!

**Comment by mukeshk** [comment]
Hi Slava,
You can revoke my access, it was amazing to work with you, and learned a
lot of things in a short time.
Thanks
M

**Comment by php-coder** [comment]
One month has passed. I'm going to cleanup the list of collaborators now.

You can join back anytime! Thank you!
