### ISSUE TITLE
Danger: handle errors from Jest

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#1564]
The puzzle `1484-67f25d21` from #1484 has to be resolved: 

https://github.com/php-coder/mystamps/blob/ad81434ad7c948fce847b89f9d005d8de4d14af8/Dangerfile#L383-L383

The puzzle was created by Slava Semushin on 10-Nov-21.

**Comment by php-coder** [comment]
I have decided discontinue usage of Danger (see #1600).
