### ISSUE TITLE
Admin can add a link to a page where someone sells this series

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#198]
When admin opens page with series info, he should see the form with the header "Add info about selling" and the following fields/labels:
- Date: optional text field, accept value in format 12.10.2012, date must be in past
- Seller: required `<select>` field, the values are populated from the `transaction_participants` table
- Url: optional text field. We can try to use `<input type="url">`. Let's try to use special validation annotation from the `hibernate-validator`
- Price: price and currency: required fields.
- Alternative price/currency: optional fields.
- Buyer: optional `<select>` field.

Additional validation: 
- buyer and seller should be different
- price and alternative price should be different

Things to not forget:
- Protect by togglz and spring security
- Protect URL for form submission by Spring Security

**Comment by php-coder** [comment]
@cssru I've updated description with my current vision.

**Comment by cssru** [comment]
Ok. But I can't see the way to add buyers and sellers to transactions_participants table. Console?

**Comment by php-coder** [comment]
We we'll implement it later.

**Comment by cssru** [comment]
> Additional validation: buyer and price should be different.

Explain, please. I thought "John Smith" and "100 USD" anyway are different.

**Comment by php-coder** [comment]
Good catch! See updated. It was a typo, I mean "buyer and seller".

**Comment by cssru** [comment]
> buyer and seller should be different

Wanna check it on backend level only or on front-end level too?

**Comment by php-coder** [comment]
We need to create (re-use?) JSR303 validator, so, yes, backend only.
