### ISSUE TITLE
Wrong series release date

### ISSUE THREAD

**Issue by cssru** [php-coder/mystamps#307]
When adding new series user can enter wrong date - for example 31.02.2014 and system shows this (wrong) date as-is.

**Comment by php-coder** [comment]
Thank you for the report! Yes, you're right, it's a bug and it's planned to this milestone: #8 (so, I'm closing this as a duplicate).

**Comment by cssru** [comment]
Oh, I'm sorry. I haven't seen it!

**Comment by cssru** [comment]
I saw possible bug when I wrote release date validator.
