### ISSUE TITLE
trello board for the project

### ISSUE THREAD

**Issue by PI-Victor** [php-coder/mystamps#324]
@php-coder now that you have some people opening pull requests and whatnot, why not try to move the wiki from github to a trello board together with the whole project information. You can create a team there, i think that in the long run it will help your project and leverage some of the milestones here.

**Comment by php-coder** [comment]
Thanks for the idea and the ticket! We're already using something like this, take a look: https://waffle.io/php-coder/mystamps

(But, probably, we should put it to a more visible place.)

**Comment by PI-Victor** [comment]
cool :+1:
