### ISSUE TITLE
UsersActivationService.findOlderThan(): add unit tests

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#337]
Tech debt for: 0fe253d7b7e7421e2c828e54c8289b3a489fdd5a (#120)

**Comment by php-coder** [comment]
@Shagbark Here should be 2 simple unit tests. I suggest to read a bit about Spock framework to understand what's going on and how it works (maybe this one: http://www.baeldung.com/groovy-spock).

Also you can use the following instruction as an example of work flow: https://github.com/php-coder/mystamps/wiki/dev_quick_start_continue

**Comment by Shagbark** [comment]
@php-coder, доброй ночи!
Вячеслав, у меня появился небольшой вопрос.
Когда добавляем RegisterAcountDto, используя метод add класса UserActivationService, то значение поля createdAt устанавливается как текущая дата. 
Как можно добавить пользователя так, что значение поля createdAt установилось иначе (допустим день назад)?

**Comment by php-coder** [comment]
> Когда добавляем RegisterAcountDto, используя метод add класса UserActivationService, то значение поля createdAt устанавливается как текущая дата.
Как можно добавить пользователя так, что значение поля createdAt установилось иначе (допустим день назад)?

С текущим кодом и в рамках юнит тестов -- никак. 

Если в целом смотреть, системно, то это возможно -- есть, например, faketime которая позволяет обмануть программу и подменить текущую дату и время.

Если рассуждать в рамках юнит-тестов, то нужно править код -- вынести `new Date()` в новый метод и затем подменять этот метод своим кодом, который бы возвращал любую другую дату (в Spock-е для этого есть Spy-объекты, если тебе интересно).

Но, это все не должно относиться к текущей задаче, так как здесь мы тестируем совсем другой метод и ничего такого сложного нам не понадобится. Просто перехвати дату, которая передается в `usersActivationDao.findOlderThan()` и проверь ее.
