### ISSUE TITLE
Add integration tests for finding series by catalog number

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#340]
- search with results
- ~~search without results~~ (extracted to #1066)
- ~~when catalogNumber unspecified~~ (extracted to #1065)
- ~~when catalogName unspecified~~ (no needed)

Tech debt for: cc61e013b5c2a5a8a7a0826b81d5ec1bcc0888e1 (#315) and 0172e38ff93718c20ecbbc0700ab52d132e0028e (#341)

--- 

Create 4 tests (one for each catalog):
- open a main page
- fill `Search by catalog` form:
  - provide an existing catalog number (let's say 99)
  - chose a catalog name (Michel/Scott/Yvert or Gibbons)
  - click on the `Search` button
- ensure that the resulted page has a series that points to `/series/1`

Requirements:
- the tests should be located in the `src/test/robotframework/series/search/logic.robot` file

Hint:
- we can use `Link Should Point To` keyword from `selenium.utils.robot` file

**Comment by mukeshk** [comment]
chose a catalogue name (Michel/Scott/Yvert or Gibbons)
- I understand this catalogue are part of the test data. We need to select catalogName from this 4 fixed items.

Am I correct

**Comment by php-coder** [comment]
Yes, here we test only between these 4 catalogs.

By the way, initially, I wrote that "Create 4 tests (one for each catalog)" but it seems that we could use Templates to reduce duplication.

Example:

https://github.com/php-coder/mystamps/blob/b65cc495618248908829e42239999297acd0a8dc/src/test/robotframework/series/creation/misc-user.robot#L22-L28

and a template:

https://github.com/php-coder/mystamps/blob/b65cc495618248908829e42239999297acd0a8dc/src/test/robotframework/series/creation/misc-user.robot#L94-L109

Here is a documentation about that: https://github.com/robotframework/QuickStartGuide/blob/836eaea991140e114fba2d11c6e31f71d787070a/QuickStart.rst#data-driven-tests

**Comment by php-coder** [comment]
@mukeshk just to ensure that we are on the same page: each issues should be addressed is a separate pull request.

**Comment by mukeshk** [comment]
in search_results.html
<a href="../series/info.html" th:href="@{${INFO_SERIES_PAGE}(id=${series.id})}">

 Need to add an id to the anchor tag.
 I think the id will be dynamic in nature, like id="series-${series..id}"

Step : Link Should Point To id="series-1"  "series/1"

**Comment by mukeshk** [comment]
Search series by existing catalog name and number 
	[Template]  Verify Series Search By Catalog By Name And Number
	michel  99
	scott  99
	yvert  99
	gibbons  99

Before Test
	Go To  ${SITE_URL}/ ${BROWSER}

Verify Series Search By Catalog By Name And Number
	[Arguments]                ${catalogName}  ${catalogNumber}
	Input Text  id=catalogNumber  ${catalogNumber}
	Select From List By Value  id=catalogName  ${catalogName}
	Submit Form                id=search-series-form
	Link Should Point To  id=series-1  ${SITE_URL}/series/1
	Go To  ${SITE_URL}

**Comment by mukeshk** [comment]
Is this good ?

**Comment by php-coder** [comment]
@mukeshk It's hard to read it here -- the code isn't highlighted and there is no indentation. Why not just create a PR where I can see and comment? :)

**Comment by php-coder** [comment]
P.S. but it seems like you're going to the right direction :)

**Comment by php-coder** [comment]
> Need to add an id to the anchor tag.

I'm not sure about this. Let's discuss in PR ;)
