### ISSUE TITLE
Don't log added catalog numbers when they weren't added

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#368]
Quote from `mvn verify` output:
```
ImageServiceImpl: Series #6: image #6 was added
MichelCatalogServiceImpl: Michel numbers [] were created
MichelCatalogServiceImpl: Series #6: michel numbers [99] were added
```
I suggest to not print `Michel numbers [] were created` when they weren't added.

**Comment by php-coder** [comment]
We should update all 4 services (not only `MichelCatalogServiceImpl`). Also, because `add()` method doesn't have unit tests yet (related issues already exist) you shouldn't add/modify any unit tests.

**Comment by cssru** [comment]
Should we print another message when no numbers were created? For example: "No Michel numbers were created"

**Comment by php-coder** [comment]
No, we shouldn't.
