### ISSUE TITLE
Generate preview for images

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#387]
For each image in a series we should have a preview. It will allow to load page faster and consume less traffic.

**Comment by php-coder** [comment]
@cssru That is what you asked me for yesterday, right?

**Comment by cssru** [comment]
Yes, it is.
--
Отправлено из Mail.Ru для Android пятница, 29 апреля 2016г., 13:56 +0300 от Vyacheslav Semushin < notifications@github.com> :

**Comment by php-coder** [comment]
* http://stackoverflow.com/a/6586065/352708
* https://github.com/rkalla/imgscalr
