### ISSUE TITLE
my-stamps.ru: move to another hosting

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#399]
Similar to #71 but we also should try to automate most of the things (see also #267). During this transition we also switch to a newer version of Ubuntu 16.04. LTS, Java and MySQL.

Subtasks:
- [x] #268 add `Vagrantfile` and setup Ansible
- [x] #269 install JDK
- [x] #270 run mystamps site with H2
- [x] #271 install nginx
- [x] Configure mysql (_manually_)
- [x] Use `prod` profile
- [x] Configure cron task for doing backups
- [x] vagrant: task `php-coder.nginx : Run and enable Nginx to start on boot` fails after removing default configuration files
- [x] Configure ssh (_manually_)
- [x] Import MySQL backup (_manually_)
- [x] Install and configure apticron (_manually_)
- [x] Configure exim (_manually_)
- [x] Configure my-stamps.ru domain's settings to point to an instance
- [x] Configure MailGun to work with a new instance (_manually_ configure domain's settings)
- [x] Create PTR record (DO already provides that for us)
- [x] Use systemd script
- [x] [Activate swap file](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04) (_manually_) (also added `vm.swappiness = 30`)
- [x] Fix deploy to the prod (`Failed to stop mystamps.service: Interactive authentication required`)

**Comment by php-coder** [comment]
For the record: I decided to not install newrelic (for Java and server monitoring), logentries and fail2ban because we have too small memory on the new server.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#998](https://github.com/php-coder/mystamps/issues/998) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the only puzzle [#998](https://github.com/php-coder/mystamps/issues/998) is solved here.
