### ISSUE TITLE
Warning from MySQL about SSL connection

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#420]
Appears in log (after #399) during mystamps service startup:
```
Tue Jul 26 01:03:42 MSK 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must
be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disa
ble SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tue Jul 26 01:03:42 MSK 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must
be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disa
ble SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

**Comment by php-coder** [comment]
If fount it in `/var/log/mystamps/mystamps.log` and looks like this message was printed with non-standard logger (maybe JUL?).

**Comment by php-coder** [comment]
@cssru Could you investigate it? First I need to understand why it happens and what are the possible solutions? Just post result of your investigation here as a comment and later we decided what to do with this issue.

**Comment by cssru** [comment]
How did you secure mysql server connections?

**Comment by cssru** [comment]
Notice that if you don't use SSL for MySQL connections you should use link like this:
jdbc:mysql://localhost:3306/mystamps?verifyServerCertificate=false&useSSL=false&requireSSL=false
instead of
jdbc:mysql://localhost:3306/mystamps.
Otherwise if you do, read this: http://stackoverflow.com/questions/14265115/configure-spring-to-connect-to-mysql-over-ssl.

**Comment by php-coder** [comment]
I don't secure connection somehow. See the `application-prod.properties` or/and `application-travis.properties`

**Comment by cssru** [comment]
So use my previous comment to avoid this warning.
