### ISSUE TITLE
SeriesController.redirectTo(): extract to ControllerUtils class

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#429]
Let's extract [SeriesController.redirectTo()](https://github.com/php-coder/mystamps/blob/9793d003ae51996e82420f3212929d220fc0ca00/src/main/java/ru/mystamps/web/controller/SeriesController.java#L385-L391) method to `ControllerUtils` class (in the same package and make it visible only for this package). To make code clean and short, we should use static import for this method.

Also, we should start using this method in `CategoryController` and `CategoryController` (search for usage of `UriComponentsBuilder.fromUriString()`).

**Comment by bodom91** [comment]
One question =)
If i want made new changes in my code (example this issue) Me need create new branch before change or after correct code and push to git ?

**Comment by php-coder** [comment]
If I correctly understand your question then you should create a branch at the beginning of work, before modifying and commiting code.

**Comment by bodom91** [comment]
Thank you !

**Comment by bodom91** [comment]
Commit https://github.com/bodom91/mystamps/commit/178d6d10d38c97d57a0b7a7c60280fe0d55c4775
But in `CountryController` have the same method [CountryController](https://github.com/php-coder/mystamps/blob/master/src/main/java/ru/mystamps/web/controller/CountryController.java#L87-L93) maybe need replace this method to ??

**Comment by php-coder** [comment]
> But in CountryController have the same method CountryController maybe need replace this method to??

Yes, they also should be replaced (as mentioned in the description: `Also, we should start using this method in CategoryController and CategoryController`).

**Comment by php-coder** [comment]
> Commit bodom91@178d6d1

Create PR, please.
