### ISSUE TITLE
Add integration test for removing series from user's collection

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#45]
When user opens series info page, he should see a button for removing series from collection. When he clicks on it, he should be redirected to collection page where this series shouldn't be listed.

Technical Debt for: 227b9a5 (#2)

**Comment by php-coder** [comment]
I've just broke it during refactoring for #440 and didn't notice that because our tests don't cover this case.

**Comment by mukeshk** [comment]
Do we consider "seriesowner" login for this test?
Series owner has "series/1"  - on collection/seriesowner page.
Should we use this as a test data? - like we remove it?

@General - Our test cases should restore the state of the system back to its original state?
Like we remove it and then should we restore it back?

**Comment by php-coder** [comment]
@mukeshk Thank you for the questions!

Yes, we should use "seriesowner" in this test.

The tests don't need to restore the state but we should keep in mind that if more than one tests share the same data, we shouldn't modify this data to keep other tests working. So, that's why in this case, I suggest to update the migration and add yet another series to "seriesowner" collection. That new series we can safely remove from his collection then.

**Comment by mukeshk** [comment]
Sure. I understand will work accordingly.

**Comment by mukeshk** [comment]
When I create a record in series, 
Do I need to create records in
Ref:  test-series-with-catalogs-numbers.sql

michel_catalog
series_michel_catalog

scott_catalog
series_scott_catalog

yvert_catalog
series_yvert_catalog

gibbons_catalog
series_gibbons_catalog

**Comment by php-coder** [comment]
No, just a series is enough. Additional meta information isn't needed as it isn't required by a test case.

**Comment by mukeshk** [comment]
sure. I am almost done with it. I just inserted in the series table before your reply.
