### ISSUE TITLE
Use versioned URLs for JS/CSS resources of external libraries

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#455]
When I'm running site with `test` profile I see that Bootstrap/jQuery/Selectize resources have the URLs without libraries' versions. This could be dangerous because browser can cache this URLs and when we update the resources, browser will continue to use their cached versions.

What should be done:
- URLs should be updated (see [Url class](https://github.com/php-coder/mystamps/blob/c5e733b6e06fd5f73fb59f85754479c8f52ffba3/src/main/java/ru/mystamps/web/Url.java#L90-L99))
- mappings for serving resources should be updated as well (see [MvcConfig class](https://github.com/php-coder/mystamps/blob/c5e733b6e06fd5f73fb59f85754479c8f52ffba3/src/main/java/ru/mystamps/web/config/MvcConfig.java#L85-L91))

**Comment by bodom91** [comment]
My commit https://github.com/bodom91/mystamps/commit/f42541e26521ae6653434b2ec13b5c95f15b3eec

**Comment by php-coder** [comment]
@bodom91 Just create PR and I'll take a look.
