### ISSUE TITLE
/category/add: prohibit repeated special characters

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#465]
When user specifies the names of category during its creation, we should validate these names and prohibit the repetition of the hyphen (for example: `te--st`). Also we should add the converter that will replace two and more spaces into single.

Note that we should apply this conversion/validation to the both fields.

What should be done:
- Add integration tests
- Add validation (`@Pattern` will be helpful)

(Extracted from #403)

**Comment by bodom91** [comment]
Hmm...
Maybe I will need add warning message - Value must not contain repetition of hyphen
Perhaps user want name `te--st` but not `te-st` ...
What do you think about that ?

**Comment by php-coder** [comment]
>Maybe I will need add warning message - Value must not contain repetition of hyphen

Warning means that user can ignore it, that this is something optional. But it should be mandatory. To understand more about why we need it, read my comments in the #403 

>Perhaps user want name te--st but not te-st ...

Note that now we're talking about country name (and not the user's login). Do you know the country that has two hyphens in its name?

P.S. "user want**S**"

**Comment by bodom91** [comment]
The title of issue  /**category**/add: prohibit repeated special characters
???))

**Comment by php-coder** [comment]
Ah, yes, I'm sorry, I've mixed the issues because they're similar. But the point is still valid: name of the category is something meaningful and from the real life (for example, Sport, Cars, Holidays, etc).

**Comment by bodom91** [comment]
Ok, will be done. =)
