### ISSUE TITLE
/series/info: null is shown when transaction doesn't have price currency

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#468]
At present field `first_currency` in the `series_sales` table allow to have `NULL` values. When I open page with series info I see the `null` as currency:

<img width="342" alt="2016-08-28 0 03 44" src="https://cloud.githubusercontent.com/assets/87088/18030354/f369f3f2-6cb2-11e6-9325-9ee0b16b90e9.png">

Related to #198

**Comment by cssru** [comment]
We should set nullable = false for first price and first currency.

**Comment by php-coder** [comment]
This issue was fixed as part of #467 when we've made both `first_price` and `first_currency` non-nullable fields.
