### ISSUE TITLE
Investigate the reason of "No TaskExecutor bean found for async processing" message

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#472]
I see the following message in the log:
```
2016-08-25 17:18:54.516  INFO 4178 --- [qtp1278852808-14] .s.a.AnnotationAsyncExecutionInterceptor : No TaskExecutor bean found for async processing
```
It scares me a bit because I don't understand what exactly it means and how it can impact to application. I would like to know and understand the reason and also decide whether we should do something with it or not.

What should be done:
- investigate the reason and post it as a comment here

**Comment by cssru** [comment]
Here is the answer https://jira.spring.io/browse/SPR-14271

**Comment by php-coder** [comment]
But he also said "I'd strongly recommend an explicit executor setup indeed". Let's configure executor for async tasks then.
