### ISSUE TITLE
User may have incomplete series in his collection

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#477]

**Comment by php-coder** [comment]
@bodom91 Could you think about this feature and suggest your vision? I have something in my mind but I think that you can try to architect it yourself. Don't try to write the code (may be you can add some HTML markup as a prototype). Do you interesting in it?

**Comment by 0pdd** [comment]
@php-coder 9 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#880](https://github.com/php-coder/mystamps/issues/880) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#875](https://github.com/php-coder/mystamps/issues/875), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#880](https://github.com/php-coder/mystamps/issues/880) are still not solved; solved: [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877).

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#875](https://github.com/php-coder/mystamps/issues/875), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#882](https://github.com/php-coder/mystamps/issues/882) are still not solved; solved: [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#880](https://github.com/php-coder/mystamps/issues/880).

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#875](https://github.com/php-coder/mystamps/issues/875), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879) are still not solved; solved: [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882).

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#887](https://github.com/php-coder/mystamps/issues/887) are still not solved; solved: [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882).

**Comment by 0pdd** [comment]
@php-coder 5 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879) are still not solved; solved: [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882), [#887](https://github.com/php-coder/mystamps/issues/887).

**Comment by 0pdd** [comment]
@php-coder 3 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874) are still not solved; solved: [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882), [#887](https://github.com/php-coder/mystamps/issues/887).

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#872](https://github.com/php-coder/mystamps/issues/872), [#874](https://github.com/php-coder/mystamps/issues/874) are still not solved; solved: [#873](https://github.com/php-coder/mystamps/issues/873), [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882), [#887](https://github.com/php-coder/mystamps/issues/887).

**Comment by 0pdd** [comment]
@php-coder the puzzle [#872](https://github.com/php-coder/mystamps/issues/872) is still not solved; solved: [#873](https://github.com/php-coder/mystamps/issues/873), [#874](https://github.com/php-coder/mystamps/issues/874), [#875](https://github.com/php-coder/mystamps/issues/875), [#876](https://github.com/php-coder/mystamps/issues/876), [#877](https://github.com/php-coder/mystamps/issues/877), [#878](https://github.com/php-coder/mystamps/issues/878), [#879](https://github.com/php-coder/mystamps/issues/879), [#880](https://github.com/php-coder/mystamps/issues/880), [#882](https://github.com/php-coder/mystamps/issues/882), [#887](https://github.com/php-coder/mystamps/issues/887).
