### ISSUE TITLE
Series sales form: price and alternative price must be different

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#504]
Tech debt for: fe9f30d (#198)

--- 

Because prices are just numbers we should check fields with currencies. In other words, it shouldn't be possible to provide prices with the same currency. The error message should be "Price and alternative price must be in a different currencies".

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1010](https://github.com/php-coder/mystamps/issues/1010) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the only puzzle [#1010](https://github.com/php-coder/mystamps/issues/1010) is solved here.
