### ISSUE TITLE
/category/add: deny "add" and "list" as category names

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#509]
Steps to reproduce:
- login as a user
- create category with name "add" (or "list")

Expected result:
- error message is shown because of invalid name

Actual result:
- category has been created and user were redirected to the `/category/add` (or `/category/list`) page

**Comment by benjiyue** [comment]
I'll take this

**Comment by php-coder** [comment]
I suggest to add validator `DenyValues` and pass disallowed values into it:

```
@DenyValues({"add", "list"})
private String name;
```

**Comment by php-coder** [comment]
I forgot to mention that you can use `@ExistingActivationKey` as an example:
- [ExistingActivationKey.java](https://github.com/php-coder/mystamps/blob/5e26ab57cd5b6a076a2eed0659b0ba1bf5b45b52/src/main/java/ru/mystamps/web/validation/jsr303/ExistingActivationKey.java)
- [ExistingActivationKeyValidator.java](https://github.com/php-coder/mystamps/blob/5e26ab57cd5b6a076a2eed0659b0ba1bf5b45b52/src/main/java/ru/mystamps/web/validation/jsr303/ExistingActivationKeyValidator.java)

If you want some theory about this, here is a link to documentation:
- [Creating custom constraints](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#validator-customconstraints)
- [Java Bean Validation Basics](http://www.baeldung.com/javax-validation)

**Comment by benjiyue** [comment]
Thus far I have written this much: https://github.com/benjiyue/mystamps/commit/b1fa3a9ee4307119194cf5bcf56819d3944e7093

But this fails compilation with the following errors:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/benjaminyue/Downloads/mystamps/src/main/java/ru/mystamps/web/model/AddCategoryForm.java:[88,21] cannot find symbol
  symbol:   method value()
  location: @interface ru.mystamps.web.validation.jsr303.DenyValues
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.850 s
[INFO] Finished at: 2017-04-14T16:44:29-04:00
[INFO] Final Memory: 42M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project mystamps: Compilation failure
[ERROR] /Users/benjaminyue/Downloads/mystamps/src/main/java/ru/mystamps/web/model/AddCategoryForm.java:[88,21] cannot find symbol
[ERROR] symbol:   method value()
[ERROR] location: @interface ru.mystamps.web.validation.jsr303.DenyValues
[ERROR] -> [Help 1]



Any pointers on what's wrong?

**Comment by php-coder** [comment]
> Any pointers on what's wrong?

You need to add `String value()` to `DenyValues` class. After that inside of `DenyValuesValidator` you will be able to invoke `annotation.value()` to get the values passed into the annotation (`@DenyValues({"add", "list"})`). With this approach you won't need to hardcode these values.

**Comment by php-coder** [comment]
P.S. We have used this approach already:
- https://github.com/php-coder/mystamps/blob/be8d102327bcc68ca256bde8aed489886bd86835/src/main/java/ru/mystamps/web/model/AddImageForm.java#L52
- https://github.com/php-coder/mystamps/blob/be8d102327bcc68ca256bde8aed489886bd86835/src/main/java/ru/mystamps/web/validation/jsr303/MaxFileSize.java#L46
- https://github.com/php-coder/mystamps/blob/be8d102327bcc68ca256bde8aed489886bd86835/src/main/java/ru/mystamps/web/validation/jsr303/MaxFileSizeValidator.java#L33

**Comment by php-coder** [comment]
@benjiyue Was it you who created categories "add" and "list" on my-stamp.ru site? Why did you create them? :)

**Comment by benjiyue** [comment]
Yeah I did. I thought categories were only local to the user account. Sorry about that

**Comment by php-coder** [comment]
Don't worry about it, I've just removed them.

>I thought categories were only local to the user account.

Interesting idea. Maybe it should be a feature OR maybe we can improve something in UX to make it more clear that categories (and countries) are global. Do you have any ideas on that?

**Comment by benjiyue** [comment]
To make is clear the user is adding a public category/country, maybe have a note on the add category page saying something like "The added category will be publicly visible". Usually with most sites all changes the user can make are local to the account and not to the whole website so that was my assumption when I created the categories to see if it would allow the "add" category. 

But if we add a feature then maybe have a checkbox. The user can tick the box to create a  global category with the default visibility being local with the box unchecked.

**Comment by php-coder** [comment]
Thank you for the feedback! I've created #559 to track it.
