### ISSUE TITLE
/country/add: deny "add" and "list" as country names

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#510]
Steps to reproduce:
- login as a user
- create country with name (in English) "add" (or "list")

Expected result:
- error message is shown because of invalid name

Actual result:
- country has been created and user was redirected to `/country/add` (or `/country/list`) page

**Comment by php-coder** [comment]
I suggest to add validator `DenyValues` and pass disallowed values into it:
```java
@DenyValues({"add", "list"})
private String name;
```

**Comment by php-coder** [comment]
@n583wxdh0j Are you still working on this issue? If not, let me know and I'll reassign this issue to someone else.

BTW validator is mostly implemented as part of #509 that will be merged soon.

**Comment by n583wxdh0j** [comment]
Give me a week.

**Comment by n583wxdh0j** [comment]
Give me a week.

**Comment by php-coder** [comment]
Ok, no problem, thanks for letting me know! Just to reminder that validator has been already implemented, so the fix will be about 3-4 lines of code (plus you should copy&paste existing test)!
