### ISSUE TITLE
Wrong kind in Russian translation

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#520]
Titiles of the default values for seller and buyer fields should be masculine when page is displayed in Russian language.

![not-choosen](https://cloud.githubusercontent.com/assets/87088/21527915/e708451e-cd2e-11e6-90ae-bb3f7f4b38a8.png)

**Comment by aarexer** [comment]
Now i see only one way to solve this issue - we can create variable with name `t_not_chosen_masculine = Не выбран` and `t_not_chosen_masculine = Not chosen`, and use it every time when we need masculine in our views.
What do you think about it?

**Comment by php-coder** [comment]
@aarexer I don't see a better way of solving this. Would you like to fix it? :)

**Comment by aarexer** [comment]
Done, you can see my pull request :)
