### ISSUE TITLE
Don't do logging to $TMPDIR/spring.log in test profile

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#531]
Need to find out why this log file is creating and disable this behavior for test profile (logging to a console is enough.

**Comment by php-coder** [comment]
@Shkarin Would you like to find out why? The first step is to identify problem.

**Comment by Shkarin** [comment]
Я попробую

2017-02-13 22:45 GMT+05:00 Vyacheslav Semushin <notifications@github.com>:

**Comment by Shkarin** [comment]
При каких действия " /tmp/spring.log" создается?

2017-02-13 23:11 GMT+05:00 Евгений Шкарин <shkarin.john@gmail.com>:

**Comment by php-coder** [comment]
> При каких действия " /tmp/spring.log" создается?

При выполнении `mvn test`

**Comment by Shkarin** [comment]
У меня файл не создается.
Файл создается, только если я добавляю
<property name="LOG_TEMP" value="./logs"/>
в logback-test.xml
Может версию поднимали spring и там уже ошибка исправилась? либо что-то не
так делаю.

2017-02-19 16:53 GMT+05:00 Vyacheslav Semushin <notifications@github.com>:

**Comment by php-coder** [comment]
Насколько понимаю, ты и не под Линуксом проверяешь. Возможно, что это линукс-специфичное. А ты у себя где файл искал, в каком каталоге?

**Comment by Shkarin** [comment]
А еще задачи есть?

20 февраля 2017 г., 21:12 пользователь Евгений Шкарин <
shkarin.john@gmail.com> написал:

**Comment by php-coder** [comment]
Да, естественно. Можешь попробовать выбрать сам:  https://github.com/php-coder/mystamps/milestone/4

**Comment by php-coder** [comment]
Точно у тебя `spring.log` не создается в текущем каталоге или в каталоге из свойства `java.io.tmpdir`?

Сейчас поэкспериментировал и, видимо, надо править `logback-test.xml`, чтобы он не настраивал логгирование в файл.

**Comment by php-coder** [comment]
Кстати, в маке файл создается в `/var/folders/j9/zjgtvd8d1r921hnbct_w42x80000gn/T/` (потому что `$TMPDIR` указывает именно на этот каталог.
