### ISSUE TITLE
Limit password length

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#543]
http://www.mscharhag.com/software-development/bcrypt-maximum-password-length

**Comment by benjiyue** [comment]
I'll take this!

**Comment by php-coder** [comment]
@benjiyue Glad to hear that! To start follow these guides:
- https://github.com/php-coder/mystamps/wiki/dev_quick_start
- https://github.com/php-coder/mystamps/wiki/dev_quick_start_continue

Also feel free to ask me about any questions that you will have.

**Comment by benjiyue** [comment]
I think I solved the problem by limiting the password length to be <=72 chars long. Is the expected error when users input longer passwords?
<img width="502" alt="screen shot 2017-03-12 at 11 20 03 am" src="https://cloud.githubusercontent.com/assets/21279383/23833012/0841efb6-0716-11e7-99c3-6f45dd96769b.png">

**Comment by php-coder** [comment]
Yes, that is exactly what I was had in mind.

**Comment by php-coder** [comment]
P.S. As far I understand the screenshot a bit outdated because it shows error for an empty input. I see that your 3rd commit fixes it.
