### ISSUE TITLE
Add integration test for maximum password length

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#545]
We already have similar test but for a minimum length: https://github.com/php-coder/mystamps/blob/2ec30d90a5e399f666b694c49986465cbfa113b9/src/test/java/ru/mystamps/web/tests/cases/WhenAnonymousUserActivateAccount.java#L216-L223

As an example this check could be used: https://github.com/php-coder/mystamps/blob/2ec30d90a5e399f666b694c49986465cbfa113b9/src/test/java/ru/mystamps/web/tests/cases/WhenAnonymousUserActivateAccount.java#L166-L173

Tech debt for: 2ec30d90a5e399f666b694c49986465cbfa113b9 (#543)

**Comment by benjiyue** [comment]
I'm on it!
