### ISSUE TITLE
/series/add: disable country suggestion when country has been specified

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#570]
We shouldn't try to suggest a country when user has already specified it in URL (e.g. `/series/add?country=italy`).

Tech debt for: 9827abb (#517)

**Comment by php-coder** [comment]
@Shkarin I fixed it with a bit Thymeleaf magick! :)

**Comment by Shkarin** [comment]
Что-то не помогло

**Comment by php-coder** [comment]
Не в тот issue ответил или правда не помогло?
