### ISSUE TITLE
/series/add: country suggestion link should work in the prototype

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#572]
When I open `src/main/webapp/WEB-INF/views/series/add.html` in a browser, link that suggest a country should work. Also it should be vertically aligned.

Tech debt for: 9827abb (#517)

**Comment by php-coder** [comment]
Also we should remove hardcoded style `position: relative; top: 7px;` and replace it by `class`, for example.

**Comment by php-coder** [comment]
P.S. we should re-use `chooseSuggestedCountry()` function for choosing a country.

**Comment by Shkarin** [comment]
>
> Also we should remove hardcoded style position: relative; top: 7px; and
> replace it by class, for example.


Я сделал это так: http://prntscr.com/f7roxa - так устроит?  или ты хочешь
через .vcenter чтоб я сделал?(с этим возникли проблемы)

When I open src/main/webapp/WEB-INF/views/series/add.html in a browser,
> link that suggest a country should work. Also it should be vertically
> aligned.

P.S. we should re-use chooseSuggestedCountry() function for choosing a
> country.


Я идею не понял если так открыть add.html то к серверу не достучится и
тогда она работать не будет ...

2017-05-07 0:42 GMT+05:00 Vyacheslav Semushin <notifications@github.com>:

**Comment by php-coder** [comment]
> Я сделал это так: http://prntscr.com/f7roxa - так устроит?

Так лучше, но давай заведем для этого отдельный класс и не будем привязываться к идентификатору элемента (в т.ч. и потому что позже нам нужно будет также выравнивать вторую ссылку с подсказкой для категории).

> или ты хочешь через .vcenter чтоб я сделал?(с этим возникли проблемы)

В идеале конечно бы переиспользовать существующие стили. А что там не получается?

Кстати, я нашел интересный ресурс по теме: http://howtocenterincss.com

> Я идею не понял если так открыть add.html то к серверу не достучится и
тогда она работать не будет ...

Идея прототипа в этом и состоит, чтобы сделать нечто похожее на рабочее приложение, но без сервера. В прототипе доступны несколько стран и мы можем без аджаксов просто выбирать одну из них. У нас там есть две функции, одна которая делает ajax-запрос, а вторая, которая выбирает страну. В случае прототипа мы можем просто вызывать вторую ф-цию напрямую.
