### ISSUE TITLE
Cleanup Togglz features

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#605]
Some of the features can be removed. Also features that have the similar authority that available only to admin should be removed. The features also should be removed from the database.

**Comment by php-coder** [comment]
The following features have been cleaned up from the code:
- SHOW_RECENT_SERIES_ON_INDEX_PAGE
- SHOW_RECENT_COLLECTIONS_ON_INDEX_PAGE
- SHOW_SEARCH_PANEL_ON_INDEX_PAGE
- LIST_CATEGORIES
- LIST_COUNTRIES
- VIEW_SITE_EVENTS
Later, their remnants can be also removed from database.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1121](https://github.com/php-coder/mystamps/issues/1121) is still not solved.

**Comment by php-coder** [comment]
Done.
