### ISSUE TITLE
/suggest/series_country: returns an empty response when there is no suggestion

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#630]
When as admin I open `/series/add` page in Firefox, I see the following error in the developer console:
```
Ошибка синтаксического анализа XML: корневой элемент не найден
Адрес: http://localhost:8080/suggest/series_country
Строка 1, символ 1:
```
It turned out that `/suggest/series_country` returns an empty response. I see that also when I'm getting the response from the terminal:
```console
$ http 'http://localhost:8080/suggest/series_country' Cookie:JSESSIONID=dyhl9vt2dr9g126hsqu0b0ict
HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 29 Aug 2017 20:43:54 GMT


```
Here the similar problem on StackOverflow: https://stackoverflow.com/questions/25650356/spring-ajax-responsebody-with-null-returned-values

Based on one of the answers, I think that we should try to return 204 No Content code and handle it accordingly on the client side.

@Shkarin JFYI

**Comment by php-coder** [comment]
I also was surprised that the response doesn't have `Content-Type` header. I think that we should add it.

**Comment by php-coder** [comment]
My current idea is to return an empty string when we can't suggest anything.

**Comment by Shkarin** [comment]
ты это сделал уже?

2017-09-15 0:41 GMT+05:00 Vyacheslav Semushin <notifications@github.com>:

**Comment by Shkarin** [comment]
и второе я так понял из этого
https://github.com/php-coder/mystamps/issues/571
ничего не реализовано?





2017-09-24 21:32 GMT+05:00 Евгений Шкарин <shkarin.john@gmail.com>:

**Comment by php-coder** [comment]
Нет по обоим вопросам. Назначь на себя и добавь метку in-progress, если хочешь ими заняться.

**Comment by Shkarin** [comment]
- user who created a series with country should see suggestion of this
   country


findCountryOfLastCreatedSeriesByUser (http://prntscr.com/gp5owz)?


   - user with a series with country in his collection should have
   suggestion for this country

findPopularCountryInCollection (http://prntscr.com/gp5og5)?



   - user who didn't create any series and doesn't have series in
   collection (or has series without country) shouldn't see suggestion link

http://prntscr.com/gp5p75 ?

Может я ошибаюсь, но вроде тесты уже на все есть, разве нет?



24 сентября 2017 г., 21:56 пользователь Vyacheslav Semushin <
notifications@github.com> написал:

**Comment by Shkarin** [comment]
My current idea is to return an empty string when we can't suggest anything.

http://prntscr.com/gp61g1 может тут проверку сделаем на нул и будем
возвращать пустую строку?

2017-09-24 23:24 GMT+05:00 Евгений Шкарин <shkarin.john@gmail.com>:

**Comment by php-coder** [comment]
> Может я ошибаюсь, но вроде тесты уже на все есть, разве нет?

This issue is about integration tests (that are using Selenium) and we only have unit tests right now.

And BTW it's better to discuss the issue in the comments to this issues.

**Comment by php-coder** [comment]
> http://prntscr.com/gp61g1 может тут проверку сделаем на нул и будем возвращать пустую строку?

Yes, let's try this.
