### ISSUE TITLE
StepDefinitions.seriesAddedToCollection(): rename method

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#643]
Method `seriesAddedToCollection()` should be renamed to `seriesHasBeenAddedToCollection()` because the latter name is more grammatically correct in English.

Tech debt for f72c87d (#46)

**Comment by Goblic** [comment]
fixed in brunch - task644

**Comment by php-coder** [comment]
@Goblic brunch it's something between breakfast and lunch ;) it should be "branch".
