### ISSUE TITLE
Move Cucumber-related classes to a separate package

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#648]
Currently `CucumberRunner` and `StepDefinitions` classes reside in `ru.mystamps.web.tests` package. Let's create a dedicated package for Cucumber-related classes -- `ru.mystamps.web.test.integration.cucumber`. Also I suggest to put all step definitions to `ru.mystamps.web.test.integration.cucumber.step` package.

Tech debt for f72c87d (#46)

**Comment by php-coder** [comment]
Update:
- `ru.mystamps.web.it.cucumber` -> `ru.mystamps.web.test.integration.cucumber`
- `ru.mystamps.web.it.cucumber.step` -> `ru.mystamps.web.test.integration.cucumber.step`

**Comment by Goblic** [comment]
fixed in brunch -task644
