### ISSUE TITLE
Ability to import a series from external site

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#660]
Admin should be able to specify a URL of a series on external site and import information about this series from that site.

**Comment by php-coder** [comment]
For the start, only category, country and image url are extracted from a page. More improvements will be added as part of separate issues.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#898](https://github.com/php-coder/mystamps/issues/898) is still not solved; solved: [#897](https://github.com/php-coder/mystamps/issues/897).
