### ISSUE TITLE
User can specify a price that he paid for a series

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#663]
It should be only available after user added this series to his collection.

**Comment by 0pdd** [comment]
@php-coder 4 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#884](https://github.com/php-coder/mystamps/issues/884), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 9 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#888](https://github.com/php-coder/mystamps/issues/888), [#889](https://github.com/php-coder/mystamps/issues/889), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884).

**Comment by 0pdd** [comment]
@php-coder 9 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#889](https://github.com/php-coder/mystamps/issues/889), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893), [#894](https://github.com/php-coder/mystamps/issues/894) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#888](https://github.com/php-coder/mystamps/issues/888).

**Comment by 0pdd** [comment]
@php-coder 8 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#889](https://github.com/php-coder/mystamps/issues/889), [#890](https://github.com/php-coder/mystamps/issues/890), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893), [#894](https://github.com/php-coder/mystamps/issues/894) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#888](https://github.com/php-coder/mystamps/issues/888), [#891](https://github.com/php-coder/mystamps/issues/891).

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#889](https://github.com/php-coder/mystamps/issues/889), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893), [#894](https://github.com/php-coder/mystamps/issues/894) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#888](https://github.com/php-coder/mystamps/issues/888), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891).

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#888](https://github.com/php-coder/mystamps/issues/888), [#889](https://github.com/php-coder/mystamps/issues/889), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#894](https://github.com/php-coder/mystamps/issues/894).

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#1024](https://github.com/php-coder/mystamps/issues/1024), [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#888](https://github.com/php-coder/mystamps/issues/888), [#889](https://github.com/php-coder/mystamps/issues/889), [#893](https://github.com/php-coder/mystamps/issues/893) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#892](https://github.com/php-coder/mystamps/issues/892), [#894](https://github.com/php-coder/mystamps/issues/894).

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#1024](https://github.com/php-coder/mystamps/issues/1024), [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#888](https://github.com/php-coder/mystamps/issues/888), [#893](https://github.com/php-coder/mystamps/issues/893) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#889](https://github.com/php-coder/mystamps/issues/889), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#892](https://github.com/php-coder/mystamps/issues/892), [#894](https://github.com/php-coder/mystamps/issues/894).

**Comment by 0pdd** [comment]
@php-coder 5 puzzles [#1024](https://github.com/php-coder/mystamps/issues/1024), [#883](https://github.com/php-coder/mystamps/issues/883), [#885](https://github.com/php-coder/mystamps/issues/885), [#886](https://github.com/php-coder/mystamps/issues/886), [#888](https://github.com/php-coder/mystamps/issues/888) are still not solved; solved: [#884](https://github.com/php-coder/mystamps/issues/884), [#889](https://github.com/php-coder/mystamps/issues/889), [#890](https://github.com/php-coder/mystamps/issues/890), [#891](https://github.com/php-coder/mystamps/issues/891), [#892](https://github.com/php-coder/mystamps/issues/892), [#893](https://github.com/php-coder/mystamps/issues/893), [#894](https://github.com/php-coder/mystamps/issues/894).
