### ISSUE TITLE
Scott catalog numbers should support letters

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#671]
At this time it's impossible to specify numbers like `2317a` because we don't accept letters. We should support letters.

**Comment by php-coder** [comment]
Ideally, we should find out a format of valid numbers. Most likely `a11`, `abb` aren't valid. Perhaps, we should allow letters only at the end.

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#972](https://github.com/php-coder/mystamps/issues/972), [#973](https://github.com/php-coder/mystamps/issues/973) are still not solved.
