### ISSUE TITLE
Search by catalog number: support searching in a user's collection

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#673]
User should be able to search by catalog number in his collection.

I suggest to add a checkbox for that. (Should we show it when collection is empty?)

Subtasks:
  - [x] #1087 add a prototype
  - [x] #1098 add the simplest implementation

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1097](https://github.com/php-coder/mystamps/issues/1097) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the only puzzle [#1097](https://github.com/php-coder/mystamps/issues/1097) is solved here.
