### ISSUE TITLE
Series sales form: don't allow to submit alternative price without currency

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#678]
Regression after #675

**Comment by php-coder** [comment]
We don't have any affected records
```
mysql> select count(*) from series_sales where second_price is not null and second_currency is null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```
so I'm going to just fix this bug without migrating existing data.

**Comment by php-coder** [comment]
There is similar bug when it's possible to specify alternative currency only. It won't be shown to user but will be written to database. There are no affected records, and I'm going to fix both bugs as part of this issue.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#1011](https://github.com/php-coder/mystamps/issues/1011) is still not solved.
