### ISSUE TITLE
SiteParser: add unit tests

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#685]
Tech debt for 29f6dc9a14606bc03a63818c59d4bbc62a18499b (#660)

**Comment by 0pdd** [comment]
@php-coder all 3 puzzles are solved here: [#752](https://github.com/php-coder/mystamps/issues/752), [#753](https://github.com/php-coder/mystamps/issues/753), [#754](https://github.com/php-coder/mystamps/issues/754).
