### ISSUE TITLE
Import series: add support for extracting catalog numbers

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#694]
Examples:
`SC# 620-22`
`Sc 1395-1403`
`M# 726-729`
`Mi 1655-1663`
`Mi# 2646-49`
`Mi# Bl 235`
`M# Block 213`
`Mi. 1519-22`
`Заг № 938-946`

Tech debt for 29f6dc9a14606bc03a63818c59d4bbc62a18499b (#660)

**Comment by php-coder** [comment]
After fixing #769 and #770 we also should support Zagorski and Solovyov catalogs.

**Comment by php-coder** [comment]
Support for Michel numbers will be added. All other catalogs will be addressed in the separate issues.

>M# 726-729
>Mi 1655-1663
>Mi# 2646-49
>Mi# Bl 235
>M# Block 213
>Mi. 1519-22

The first, very naive implementation only supports numbers in a form `M# 726-729`.

**Comment by 0pdd** [comment]
@php-coder 16 puzzles [#902](https://github.com/php-coder/mystamps/issues/902), [#903](https://github.com/php-coder/mystamps/issues/903), [#904](https://github.com/php-coder/mystamps/issues/904), [#905](https://github.com/php-coder/mystamps/issues/905), [#906](https://github.com/php-coder/mystamps/issues/906), [#907](https://github.com/php-coder/mystamps/issues/907), [#908](https://github.com/php-coder/mystamps/issues/908), [#909](https://github.com/php-coder/mystamps/issues/909), [#910](https://github.com/php-coder/mystamps/issues/910), [#911](https://github.com/php-coder/mystamps/issues/911), [#912](https://github.com/php-coder/mystamps/issues/912), [#913](https://github.com/php-coder/mystamps/issues/913), [#914](https://github.com/php-coder/mystamps/issues/914), [#915](https://github.com/php-coder/mystamps/issues/915), [#916](https://github.com/php-coder/mystamps/issues/916), [#917](https://github.com/php-coder/mystamps/issues/917) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 15 puzzles [#902](https://github.com/php-coder/mystamps/issues/902), [#904](https://github.com/php-coder/mystamps/issues/904), [#905](https://github.com/php-coder/mystamps/issues/905), [#906](https://github.com/php-coder/mystamps/issues/906), [#907](https://github.com/php-coder/mystamps/issues/907), [#908](https://github.com/php-coder/mystamps/issues/908), [#909](https://github.com/php-coder/mystamps/issues/909), [#910](https://github.com/php-coder/mystamps/issues/910), [#911](https://github.com/php-coder/mystamps/issues/911), [#912](https://github.com/php-coder/mystamps/issues/912), [#913](https://github.com/php-coder/mystamps/issues/913), [#914](https://github.com/php-coder/mystamps/issues/914), [#915](https://github.com/php-coder/mystamps/issues/915), [#916](https://github.com/php-coder/mystamps/issues/916), [#917](https://github.com/php-coder/mystamps/issues/917) are still not solved; solved: [#903](https://github.com/php-coder/mystamps/issues/903).
