### ISSUE TITLE
Validate year of release

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#7]
Add `year` field validation at series creation page. It must be inside range [1840, $currentYear].

**Comment by php-coder** [comment]
Because we already has a check for the year in future (see #8) then here we just need to check that the year >= 1840. I suggest to use `@Min` annotation for that.

**Comment by cssru** [comment]
Ага, а я думал - на стороне клиента проверку реализовать.

**Comment by php-coder** [comment]
Technically it's already "validated" on the client side -- there is a select with options from 1840 to 2016. So, just user couldn't choose the year less than 1840. But... this check intended not for ordinary users :)

**Comment by cssru** [comment]
Year, angry users may want to put your app down, right?

**Comment by php-coder** [comment]
:-) No, probably, it can't broke the application, but a) I want to be sure that my data satisfies the constraints b) it's a trivial task that could be accomplished by newcomers :)

BTW, if we would use PostgreSQL, for instance, we could add a `CHECK()` constraint (I don't try it, but looks like we could).

Another idea about protecting the data is: maybe we could write some logic that operates on the series' year and if someone put `-1` as the year this logic could go crazy :)
