### ISSUE TITLE
Import series: connect import request with created series

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#700]
When import request is successful, we should show a link to a page with series.

**Comment by php-coder** [comment]
Note, that currently there is no code that will change request status from `ParsingSucceeded` into `ImportSucceeded`.

**Comment by php-coder** [comment]
Don't forget to add an integration test.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#757](https://github.com/php-coder/mystamps/issues/757) is still not solved; solved: [#734](https://github.com/php-coder/mystamps/issues/734), [#735](https://github.com/php-coder/mystamps/issues/735), [#736](https://github.com/php-coder/mystamps/issues/736), [#756](https://github.com/php-coder/mystamps/issues/756).
