### ISSUE TITLE
Support for Zagorski catalogue

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#769]
In Russian: https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82-%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F_(%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3_%D0%BC%D0%B0%D1%80%D0%BE%D0%BA)

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#773](https://github.com/php-coder/mystamps/issues/773), [#775](https://github.com/php-coder/mystamps/issues/775) are still not solved; solved: [#776](https://github.com/php-coder/mystamps/issues/776), [#809](https://github.com/php-coder/mystamps/issues/809), [#810](https://github.com/php-coder/mystamps/issues/810).
