### ISSUE TITLE
EventsConfig.createSiteParsers(): split the logic

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#804]
The puzzle `801-71f4f89c` from #801 has to be resolved:

https://github.com/php-coder/mystamps/blob/0dac42b5f29df81a50de52b6b8142aa87bce142f/src/main/java/ru/mystamps/web/config/EventsConfig.java#L148-L149

The puzzle was created by Slava Semushin on 02-Jan-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by php-coder** [comment]
The idea is to parse properties, put them in a `Map<String, String>` and pass it to builder that will create a fully-initialized object. It separates logic and also allows us to remove `setField()` and `isFullyInitialized` from `SiteParser` interface.

This also could solve `ModifiedCyclomaticComplexity` warning from PMD.

**Comment by php-coder** [comment]
We won't have such log after migrating site parsers configuration to database (see #975)
