### ISSUE TITLE
TimedSiteParser: add unit tests

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#805]
The puzzle `801-b1837c29` from #801 has to be resolved:

https://github.com/php-coder/mystamps/blob/0dac42b5f29df81a50de52b6b8142aa87bce142f/src/main/java/ru/mystamps/web/util/extractor/TimedSiteParser.java#L27-L27

The puzzle was created by Slava Semushin on 02-Jan-18.

**Comment by php-coder** [comment]
Perhaps we can wait until #804 will be fixed (it should reduce number of methods in the interface).
