### ISSUE TITLE
Series import: make lookup for a category/country case insensitive

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#819]

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#825](https://github.com/php-coder/mystamps/issues/825), [#827](https://github.com/php-coder/mystamps/issues/827) are still not solved; solved: [#824](https://github.com/php-coder/mystamps/issues/824), [#826](https://github.com/php-coder/mystamps/issues/826).
