### ISSUE TITLE
Series import: filter out invalid candidates

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#821]
We should filter out candidates with short names because otherwise they can match when we'll use `LIKE` and leads to a wrong category:
```
r.m.w.s.SeriesInfoExtractorServiceImpl   : Determining category from a fragment: 'ДАГОМЕЯ ? М? ДОИСТОРИЧЕСКАЯ ФАУНА ДИНОЗАВРЫ АВИАПОЧТА 3 БЕЗЗУБЦОВЫЕ МАРКИ С ПОЛЯМИ КУПИТЬ! (39)'
r.m.w.s.SeriesInfoExtractorServiceImpl   : Possible candidates: [С, М?, ФАУНА, (39), 3, БЕЗЗУБЦОВЫЕ, ПОЛЯМИ, ДОИСТОРИЧЕСКАЯ, ДИНОЗАВРЫ, МАРКИ, АВИАПОЧТА, ДАГОМЕЯ, ?, КУПИТЬ!]
r.m.w.s.SeriesInfoExtractorServiceImpl   : Found categories: []
r.m.w.s.SeriesInfoExtractorServiceImpl   : Possible candidate: 'С%'
r.m.w.s.SeriesInfoExtractorServiceImpl   : Found categories: [2]
```
The result is wrong because `2` is id of the `Sport` category, while I expect that it should found "Prehistoric animals" category.

Also let's filter out candidates with long names.

Perhaps, after fixing #819 it will find "Prehistoric animals" category from the first attempt (via aliases) and won't produce wrong result (because it won't do lookup with `LIKE`).

**Comment by 0pdd** [comment]
@php-coder all 2 puzzles are solved here: [#822](https://github.com/php-coder/mystamps/issues/822), [#823](https://github.com/php-coder/mystamps/issues/823).
