### ISSUE TITLE
Import series: assign group during seller creation

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#857]
Tech debt for: 0acabfc77684abc22c1e94d7f75b25d12bf8206d (#695)

**Comment by 0pdd** [comment]
@php-coder 7 puzzles [#918](https://github.com/php-coder/mystamps/issues/918), [#919](https://github.com/php-coder/mystamps/issues/919), [#920](https://github.com/php-coder/mystamps/issues/920), [#921](https://github.com/php-coder/mystamps/issues/921), [#922](https://github.com/php-coder/mystamps/issues/922), [#923](https://github.com/php-coder/mystamps/issues/923), [#924](https://github.com/php-coder/mystamps/issues/924) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#918](https://github.com/php-coder/mystamps/issues/918), [#919](https://github.com/php-coder/mystamps/issues/919), [#920](https://github.com/php-coder/mystamps/issues/920), [#922](https://github.com/php-coder/mystamps/issues/922), [#923](https://github.com/php-coder/mystamps/issues/923), [#924](https://github.com/php-coder/mystamps/issues/924) are still not solved; solved: [#921](https://github.com/php-coder/mystamps/issues/921).

**Comment by 0pdd** [comment]
@php-coder 5 puzzles [#918](https://github.com/php-coder/mystamps/issues/918), [#919](https://github.com/php-coder/mystamps/issues/919), [#922](https://github.com/php-coder/mystamps/issues/922), [#923](https://github.com/php-coder/mystamps/issues/923), [#924](https://github.com/php-coder/mystamps/issues/924) are still not solved; solved: [#920](https://github.com/php-coder/mystamps/issues/920), [#921](https://github.com/php-coder/mystamps/issues/921).
