### ISSUE TITLE
Add integration tests for collection estimation page

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#893]
The puzzle `884-d2a3ddba` from #884 has to be resolved:

https://github.com/php-coder/mystamps/blob/9287473f424222a3ead476ee7be30960c2c6dfcf/src/main/java/ru/mystamps/web/controller/CollectionController.java#L107-L107

The puzzle was created by Slava Semushin on 20-Jun-18.

---

I see that we can have at least the following 3 tests:

0) Before Test Suite:
    - login as `paid` user (with a password `test`)

1) Message should be shown when a collection is empty
    - open `/collection/paid/estimation`
    - the message "In this collection is no stamps" should be shown

2) Series with its price should be taken into account
    - open `/series/1` and it to the collection with a some price (let's use 100) and random currency
    - open `/collection/paid/estimation` page
    - the series should be listed and price should be 100 $currency (perhaps, we can use `Table Row Should Contain` for that? or `Get Table Cell`)
    - Total should be 100 $currency (perhaps, we can use `Table Footer Should Contain` for that?)

3) Series without price should be shown but not taken into account
    - open `/series/2`
    - add this series without specifying a price
    - the series should be listed without price
    - Total should be the same as before (100 $currency)

Notes:
- test cases should be placed into `src/test/robotframework/collection/estimation/logic.robot` file

**Comment by mukeshk** [comment]
"Selenium.Utils.Robot": Select Random Option From List, - doesn't support option to skip a blank option element. Can I add an argument startIndex, which will indicate the start index in the options list?  
So if we configure, 
Select Random Option From List id="paid-currency" 1
in another place, where the first option is not blank we can pass
Select Random Option From List  id=catalogName 0

**Comment by php-coder** [comment]
@mukeshk Thank you for the good question! Yes, I think we should modify this keyword and re-use it. But I'd suggest to implement it a little differently:
- add parameter "ignoreEmptyOption" and set it to "false" by default (for backward compatibility)
- use if + [`Remove Values From List`](http://robotframework.org/robotframework/3.0.3/libraries/Collections.html#Remove%20Values%20From%20List) to remove an empty value

WDYT?

**Comment by mukeshk** [comment]
I was thinking about boolean was not sure how I could manipulate list in
robot script.

I agree with your suggestions. Will check it out.

Thanks and best regards
Mukesh

**Comment by php-coder** [comment]
@mukeshk Very good point!

I agree that we should use `Select From List By Value` instead of `Select From List By Index` in this case.

>     Select From List By Value  ${locator}  ${randomValue}

Should be something like

```
     Select From List By Value  ${locator}  @{options}[${randomValue}]
```

**Comment by php-coder** [comment]
P.S. https://stackoverflow.com/questions/42576003/fetch-value-from-list-in-robot-framework might be helpful.

**Comment by mukeshk** [comment]
![image](https://user-images.githubusercontent.com/1241720/63921194-fc977900-ca5f-11e9-963f-070333164001.png)

Remove Values From List  ${options}  ""  ' '  ''  null     is not working as expected.
the original drop-down contains five options.

![image](https://user-images.githubusercontent.com/1241720/63921372-5009c700-ca60-11e9-8009-a2509de49bad.png)

Should we change the first option to value="" in the series/info.html.

**Comment by mukeshk** [comment]
![image](https://user-images.githubusercontent.com/1241720/63921496-88110a00-ca60-11e9-9f52-9e86c3590c5e.png)

in the collection\estimation.html page - for the cell are represented by th instead of td. 
the keyword "Table Footer Should Contain"  works with tfoot - containing - td .
it does not work with a tfoot containing th.

If I convert the th to td, we lose the bold formatting, should i apply bold tag to the <td> content so that it looks like th - text content.

**Comment by mukeshk** [comment]
We get the data table error after we submit the "add-series-form".
The same which is due to the charts. So this test also we need to tag as unstable.

**Comment by php-coder** [comment]
> Remove Values From List ${options} "" ' ' '' null is not working as expected.

It's now what I expected actually :) Would it work with `${EMPTY}`?

```
Remove Values From List ${options}  ${EMPTY}
```

**Comment by php-coder** [comment]
> The keyword "Table Footer Should Contain" works with tfoot - containing - td . it does not work with a tfoot containing th.

Thanks for finding and reporting this! I've done the same -- reported it back to upstream: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/88

As I looked to the sources I found out that due to a little weird behavior of "Table Header Should Contain" we can use it for checking the footer :) See https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/89 for details.

What do you think?

**Comment by php-coder** [comment]
P.S. Anyway, it both these keywords won't work for us, we can get elements and their text by CSS/XPath/etc as we do with other elements.

**Comment by php-coder** [comment]
> We get the data table error after we submit the "add-series-form". The same which is due to the charts. So this test also we need to tag as unstable.

Hm, you're right. Thank you for letting me know.

By the way, if you have a code, it's always better to discuss details in the PR ;)

**Comment by mukeshk** [comment]
> > Remove Values From List ${options} "" ' ' '' null is not working as expected.
> 
> It's not what I expected actually :) Would it work with `${EMPTY}`?
> 
> ```
> Remove Values From List ${options}  ${EMPTY}
> ```

You rock !!! it works :)

**Comment by mukeshk** [comment]
> > The keyword "Table Footer Should Contain" works with tfoot - containing - td . it does not work with a tfoot containing th.
> 
> Thanks for finding and reporting this! I've done the same -- reported it back to upstream: [Hi-Fi/robotframework-seleniumlibrary-java#88](https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/88)
> 
> As I looked to the sources I found out that due to a little weird behavior of "Table Header Should Contain" we can use it for checking the footer :) See [Hi-Fi/robotframework-seleniumlibrary-java#89](https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/89) for details.
> 
> What do you think?

Again Table Header Should Contain ... It works.
