### ISSUE TITLE
/collection/{slug}/estimation: optimize summing of prices */-->

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#894]
The puzzle `884-898a9e3d` from #884 has to be resolved:

https://github.com/php-coder/mystamps/blob/524a9b3aedd30535bbd010d40b1673671ccab77a/src/main/webapp/WEB-INF/views/collection/estimation.html#L118-L118

The puzzle was created by Slava Semushin on 21-Jun-18.

**Comment by php-coder** [comment]
Duplicate of #888
