### ISSUE TITLE
JdbcSeriesImportDao.changeStatus(): introduce dto

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#897]
The puzzle `660-d185398d` from #660 has to be resolved:

https://github.com/php-coder/mystamps/blob/74259de0816bebb535dff1315b2988daa3a379fa/src/main/java/ru/mystamps/web/dao/impl/JdbcSeriesImportDao.java#L134-L134

The puzzle was created by Slava Semushin on 05-Jul-18.

---

We need to modify `changeStatus()` method in the `JdbcSeriesImportDao` class. At this moment it has 4 arguments and we need to extract them into a single class. I suggest to give it a name `UpdateImportRequestStatusDbDto`.

The class has been renamed some time ago and now its new location is `src/main/java/ru/mystamps/web/feature/series/importing/JdbcSeriesImportDao.java`

**Comment by php-coder** [comment]
CC @KrivenkoAlexander
