### ISSUE TITLE
Split packages by features

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#927]
Let's try to do an experiment by split packages by features. I expect that a package with particular feature will have everything that it is required: controller, service, dao, etc.

Candidates:
- [x] category
- [x] country
- [x] series (depends on category and country features)
- [x] account
- [x] collection
- [x] series import
- [x] series sales
- [x] series sales import
- [x] transaction participant
- [x] image
- [x] report
- [x] mail
- [x] site
- [x] common

**Comment by 0pdd** [comment]
@php-coder the puzzle [#932](https://github.com/php-coder/mystamps/issues/932) is still not solved.

**Comment by 0pdd** [comment]
@php-coder the only puzzle [#932](https://github.com/php-coder/mystamps/issues/932) is solved here.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#974](https://github.com/php-coder/mystamps/issues/974) is still not solved; solved: [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 4 puzzles [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 13 puzzles [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 16 puzzles [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by php-coder** [comment]
A lot of work have been done. While some small issues left, they're related to dependencies between packages rather than split itself. Let's close the issue!

**Comment by 0pdd** [comment]
@php-coder 15 puzzles [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#1036](https://github.com/php-coder/mystamps/issues/1036), [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 14 puzzles [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 13 puzzles [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 12 puzzles [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#932](https://github.com/php-coder/mystamps/issues/932).

**Comment by 0pdd** [comment]
@php-coder 11 puzzles [#1040](https://github.com/php-coder/mystamps/issues/1040), [#1041](https://github.com/php-coder/mystamps/issues/1041), [#1042](https://github.com/php-coder/mystamps/issues/1042), [#1043](https://github.com/php-coder/mystamps/issues/1043), [#1044](https://github.com/php-coder/mystamps/issues/1044), [#1045](https://github.com/php-coder/mystamps/issues/1045), [#1046](https://github.com/php-coder/mystamps/issues/1046), [#1047](https://github.com/php-coder/mystamps/issues/1047), [#1048](https://github.com/php-coder/mystamps/issues/1048), [#1051](https://github.com/php-coder/mystamps/issues/1051), [#974](https://github.com/php-coder/mystamps/issues/974) are still not solved; solved: [#1036](https://github.com/php-coder/mystamps/issues/1036), [#1037](https://github.com/php-coder/mystamps/issues/1037), [#1038](https://github.com/php-coder/mystamps/issues/1038), [#1052](https://github.com/php-coder/mystamps/issues/1052), [#1053](https://github.com/php-coder/mystamps/issues/1053), [#932](https://github.com/php-coder/mystamps/issues/932).
