### ISSUE TITLE
Series import: move configuration of the site parsers to database

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#975]
At this moment, site parsers configuration is staticly defined in the `application.properties` file(s). It means that when we add one more parser or changes the property of one of the existing, we have to restart the application.

The first issue, that once broke the site already, is that ansible role doesn't support `app.site-parsers*` properties yet (see #929). If we move these properties to database, we won't need such a support at all.

The second issue is that restarting of the application slow us down when we working on the adding a new site parser. If we would have such configuration in database, we won't have this difficulty and adding a new site parser (or fixing the existing one) will be much faster. In this case, we should read the configuration from database not just once, during application startup, but for every import request.

**Comment by 0pdd** [comment]
@php-coder the puzzle [#982](https://github.com/php-coder/mystamps/issues/982) is still not solved.

**Comment by 0pdd** [comment]
@php-coder 2 puzzles [#982](https://github.com/php-coder/mystamps/issues/982), [#983](https://github.com/php-coder/mystamps/issues/983) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 3 puzzles [#982](https://github.com/php-coder/mystamps/issues/982), [#983](https://github.com/php-coder/mystamps/issues/983), [#984](https://github.com/php-coder/mystamps/issues/984) are still not solved.

**Comment by php-coder** [comment]
Done!
