### ISSUE TITLE
Series Import: DataIntegrityViolationException for a long URL

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#990]
We have mismatched length for the following fields:
- `series_import_requests.url` varchar(767)
- `series_sales.transaction_url` varchar(255)
And when we import a series with a URL longer than 255 characters, we get DataIntegrityViolationException.
---

Steps to reproduce:
1) run wiremock server: `mvn wiremock:run -DkeepRunning=true`
2) login as admin
3) go to import series page (http://localhost:8080/series/import/request)
4) import a page with a URL longer than 255 characters:
    http://127.0.0.1:8888/series/import/request-logic/new-seller.html?test=0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
5) on the next page, submit a form with provided data

Actual result:
- "Internal server error" page is shown
- the server outputs the error:
```
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT INTO series_sales ( series_id , date , seller_id , transaction_url , first_price , first_currency , second_price , second_currency , buyer_id , created_at , created_by ) VALUES ( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? )]; Value too long for column "TRANSACTION_URL VARCHAR(255)": "'http://127.0.0.1:8888/series/import/request-logic/new-seller.html?test=01234567890123456789012345678901234567890123456789012345... (261)"; SQL statement:
INSERT INTO series_sales ( series_id , date , seller_id , transaction_url , first_price , first_currency , second_price , second_currency , buyer_id , created_at , created_by ) VALUES ( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ) [22001-197]; nested exception is org.h2.jdbc.JdbcSQLException: Value too long for column "TRANSACTION_URL VARCHAR(255)": "'http://127.0.0.1:8888/series/import/request-logic/new-seller.html?test=01234567890123456789012345678901234567890123456789012345... (261)"; SQL statement:
INSERT INTO series_sales ( series_id , date , seller_id , transaction_url , first_price , first_currency , second_price , second_currency , buyer_id , created_at , created_by ) VALUES ( ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? ) [22001-197]
```

Expected result:
- Page should be imported successfully

**Comment by php-coder** [comment]
@mihnayan Hi, how about this one? The only thing that is required here is to provide a database migration (liquibase). Assign the issue to self if you ready to work on it.

Ask me about steps to reproduce the issue if you need.

**Comment by mihnayan** [comment]
@php-coder Do I understand correctly that this bug is reproduced on the "Image URL" field of the "/series/add" page? Have you got example of the long url?

**Comment by php-coder** [comment]
@mihnayan Thank you for the question! This is a little different case. I've updated the issue description and included the steps to reproduce the bug locally.

If you need a full picture, here is the overview:
- we have a feature where it's possible to import information about series from external site. User submits a URL (that is saved to `series_import_requests.url`), the site downloads it and parses its content. The parsed values are persisted to the database and later user can review them, fill required values and create a series.
- at some point, this feature was enhanced: it became possible to also import information about a seller. So, now it also possible to extract information like "Slava is selling this series by that URL for 200 RUB". The URL in that case is the page from where we import the series from. This URL is saved into `series_sales.transaction_url` field.

The bug appears because `series_import_requests.url` field has greater length than `series_sales.transaction_url` and hence we can't save a long URL into that field.

This issue is about setting the length of the `series_sales.transaction_url` field to the length of the `series_import_requests.url`.

**Comment by mukeshk** [comment]
There was a pull which is not complete.
https://github.com/php-coder/mystamps/pull/1013
Need to set SeriesSalesDb.SeriesSales.TRANSACTION_URL_LENGTH = 767

append to > version/0.4.xml
<include file="0.4/2019-07-20--series_sales_transaction_url_length.xml" relativeToChangelogFile="true"/>

This should work.
<modifyDataType tableName="series_sales" columnName="transaction_url" newDataType="VARCHAR(767)" />
	
 <renameColumn 
            columnDataType="VARCHAR(767)"
            newColumnName="transaction_url"
            oldColumnName="transaction_url"
            remarks="Must match to the series_import_requests.url field"        
            tableName="series_sales"/>

the "columnDataType" is required in case of MySQL
https://www.liquibase.org/documentation/changes/rename_column.html

Is it all required ? or am I missing something?

**Comment by php-coder** [comment]
@mukeshk Yes, you're right. I can't merge this PR because it's incomplete and has conflicts, so we need to re-write it.

Keep in mind, that a migration now should be placed into `src/main/resources/liquibase/version/0.4.1` directory. Also, we need to create `src/main/resources/liquibase/version/0.4.1.xml` and include it from within `src/main/resources/liquibase/changelog.xml`)

**Comment by mukeshk** [comment]
My test setup changed the application-test properties to connect to local MySQL.
configured liquibase to run only the rename command with remarks and data type.
Started application mvn spring-boot: run

![image](https://user-images.githubusercontent.com/1241720/61594624-8ce5d100-ac0b-11e9-8584-18fa8f5d3f96.png)

**Comment by php-coder** [comment]
@mukeshk Thank you for the screenshot! It helped me realized that this comment should be on series_import_requests table, not on the series_sales :-/ Could you update PR to remove `remarks` then? I'm sorry.

**Comment by mukeshk** [comment]
ok. So should I change the liquibase instruction back to 
`<modifyDataType tableName="series_sales" columnName="transaction_url" newDataType="VARCHAR(767)" />
`
and no renamecolumn instruction for the comment. 
Is that good?

**Comment by php-coder** [comment]
> Is that good?

Yes, it seems like yes.
