### ISSUE TITLE
Add integration tests for showing similar series

### ISSUE THREAD

**Issue by 0pdd** [php-coder/mystamps#993]
The puzzle `967-57830854` from #967 has to be resolved: 

https://github.com/php-coder/mystamps/blob/054f826ef6706f82b4a7c04d73715d161d0c1a28/src/main/webapp/WEB-INF/views/series/info.html#L342-L342

The puzzle was created by Slava Semushin on 23-Dec-18.

---

- we need to create 2 series and mark them as similar
- as anonymous user open a page with the first of series, check that:
   - ~~there is a block with header "Similar series"~~
   - this block has a link to another series
- click on that series
- on the page with another series, check that:
   - ~~there is a block with header "Similar series"~~
   - this block has a link to the first series

**Comment by 0pdd** [comment]
The puzzle `967-57830854` has disappeared from the source code, that's why I closed this issue.

**Comment by php-coder** [comment]
It's still there but it was closed (and a new one was created) because of the bug in pdd/0pdd.

**Comment by mukeshk** [comment]
1. Create a new Test data script
    Create 2 new records in series and make an entry in the similar_series table 
2.  Should we use the select max strategy to fetch the newly assigned primary key for the series table?
3.  Which User I should assign to the new series record?

**Comment by php-coder** [comment]
> Which User I should assign to the new series record?

This is available for all users, including non-authenticated, so let's use anonymous user.

**Comment by mukeshk** [comment]
Not for search function, but for the user on the series table.

**Comment by php-coder** [comment]
> Should we use the select max strategy to fetch the newly assigned primary key for the series table?

In the commit 0131f329323c2a0d49da0c28252c429101122fae I've started to use a little different approach. Every series should have a quantity that matches its id. So, in order to get id of the series we can select by its quantity (see the commits for example).

**Comment by php-coder** [comment]
> Not for search function, but for the user on the series table.

User anonymous user for all these tests.
