### ISSUE TITLE
Series sale: import automatically by URL

### ISSUE THREAD

**Issue by php-coder** [php-coder/mystamps#995]

**Comment by php-coder** [comment]
During deploy we should update `application-prod.properties` to remove `org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration` class from `spring.autoconfigure.exclude`.

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#1025](https://github.com/php-coder/mystamps/issues/1025), [#1026](https://github.com/php-coder/mystamps/issues/1026), [#1027](https://github.com/php-coder/mystamps/issues/1027), [#1028](https://github.com/php-coder/mystamps/issues/1028), [#1029](https://github.com/php-coder/mystamps/issues/1029), [#1030](https://github.com/php-coder/mystamps/issues/1030) are still not solved.

**Comment by 0pdd** [comment]
@php-coder 6 puzzles [#1025](https://github.com/php-coder/mystamps/issues/1025), [#1026](https://github.com/php-coder/mystamps/issues/1026), [#1028](https://github.com/php-coder/mystamps/issues/1028), [#1029](https://github.com/php-coder/mystamps/issues/1029), [#1030](https://github.com/php-coder/mystamps/issues/1030), [#1079](https://github.com/php-coder/mystamps/issues/1079) are still not solved; solved: [#1027](https://github.com/php-coder/mystamps/issues/1027).

**Comment by 0pdd** [comment]
@php-coder 5 puzzles [#1025](https://github.com/php-coder/mystamps/issues/1025), [#1028](https://github.com/php-coder/mystamps/issues/1028), [#1029](https://github.com/php-coder/mystamps/issues/1029), [#1030](https://github.com/php-coder/mystamps/issues/1030), [#1079](https://github.com/php-coder/mystamps/issues/1079) are still not solved; solved: [#1026](https://github.com/php-coder/mystamps/issues/1026), [#1027](https://github.com/php-coder/mystamps/issues/1027).
